Fix retiming base streams for prebuilt binaries

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -85,7 +85,8 @@ jobs:
             --disable-encoders --disable-hwaccels --disable-muxers --disable-protocols --disable-devices --disable-filters \
             --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 \
             --disable-avx2 --disable-avx512 --disable-avx512icl --disable-aesni --disable-clmul \
-            --disable-shared --enable-static --enable-muxer=matroska --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic || {
+            --disable-shared --enable-static --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic \
+            --enable-muxer=matroska --enable-muxer=matroska_audio --enable-muxer=ass --enable-muxer=srt --enable-muxer=webvtt || {
               echo "=== CONFIGURATION FAILED ==="
               cat ffbuild/config.log
               exit 1
@@ -103,22 +104,69 @@ jobs:
           path: target/${{ matrix.target }}/release/mux-media.exe
 
 
-  macos-arm64-build:
+  macos-builds:
     runs-on: macos-latest
+
+    env:
+      FFMPEG_DIR: ${{ github.workspace }}/target/mux-media-ffmpeg
+
+      CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS: "-C target-cpu=core2"
+      CC_x86_64_apple_darwin: "clang -arch x86_64"
+      CXX_x86_64_apple_darwin: "clang++ -arch x86_64"
+      RC_ARCHS_x86_64_apple_darwin: "x86_64"
+
+    strategy:
+      matrix:
+        include:
+          - target: aarch64-apple-darwin
+            ffmpeg_configure_flags: --arch=arm64
+            release_suffix: macOS-arm64
+
+          - target: x86_64-apple-darwin
+            ffmpeg_configure_flags: --arch=x86_64 --cc="clang -arch x86_64" --extra-cflags="-arch x86_64 -march=core2" --extra-ldflags="-arch x86_64"
+            release_suffix: macOS-x64
 
     steps:
       - uses: actions/checkout@v4
 
-      - name: Install dependencies
-        run: brew install pkg-config ffmpeg
+      - name: Install Rust target
+        run: rustup target add ${{ matrix.target }}
+
+      - name: Install Dependencies
+        run: |
+          brew update
+          brew install nasm make
+
+      - name: Build & Install static FFmpeg
+        run: |
+          SRC_DIR="${{ github.workspace }}/target/ffmpeg-src"
+
+          git clone --depth 1 --branch n8.1.2 https://github.com/ffmpeg/ffmpeg $SRC_DIR
+          cd $SRC_DIR
+          ./configure --target-os=darwin --prefix="${{ env.FFMPEG_DIR }}" \
+            ${{ matrix.ffmpeg_configure_flags }} --pkg-config-flags="--static" \
+            --disable-runtime-cpudetect --disable-autodetect --disable-programs --disable-doc \
+            --disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-network \
+            --disable-encoders --disable-hwaccels --disable-muxers --disable-protocols --disable-devices --disable-filters \
+            --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 \
+            --disable-avx2 --disable-avx512 --disable-avx512icl --disable-aesni --disable-clmul \
+            --disable-shared --enable-static --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic \
+            --enable-muxer=matroska --enable-muxer=matroska_audio --enable-muxer=ass --enable-muxer=srt --enable-muxer=webvtt || {
+              echo "=== CONFIGURATION FAILED ==="
+              cat ffbuild/config.log
+              exit 1
+            }
+
+            make -j$(sysctl -n hw.ncpu)
+            make install
 
       - name: Build
-        run: cargo build --release --features ffmpeg-build
+        run: cargo build --release --features ffmpeg-static --target ${{ matrix.target }}
 
       - uses: actions/upload-artifact@v4
         with:
-          name: mux-media-macOS-arm64
-          path: target/release/mux-media
+          name: mux-media-${{ matrix.release_suffix }}
+          path: target/${{ matrix.target }}/release/mux-media
 
 
   linux-builds:
@@ -177,7 +225,7 @@ jobs:
 
   github-release:
     runs-on: ubuntu-latest
-    needs: [cargo-publish-dry-run, windows-builds, macos-arm64-build, linux-builds]
+    needs: [cargo-publish-dry-run, windows-builds, macos-builds, linux-builds]
 
     steps:
       - uses: actions/download-artifact@v4
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -49,7 +49,8 @@ jobs:
             --disable-encoders --disable-hwaccels --disable-muxers --disable-protocols --disable-devices --disable-filters \
             --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 \
             --disable-avx2 --disable-avx512 --disable-avx512icl --disable-aesni --disable-clmul \
-            --disable-shared --enable-static --enable-muxer=matroska --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic || {
+            --disable-shared --enable-static --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic \
+            --enable-muxer=matroska --enable-muxer=matroska_audio --enable-muxer=ass --enable-muxer=srt --enable-muxer=webvtt || {
               echo "=== CONFIGURATION FAILED ==="
               cat ffbuild/config.log
               exit 1
@@ -64,15 +65,42 @@ jobs:
 
   macos-arm64-static:
     runs-on: macos-latest
+    env:
+      FFMPEG_DIR: ${{ github.workspace }}/target/aarch64-apple-darwin/mux-media-ffmpeg
 
     steps:
       - uses: actions/checkout@v4
 
-      - name: Install dependencies
-        run: brew install pkg-config ffmpeg
+      - name: Install Dependencies
+        run: |
+          brew update
+          brew install nasm make
+
+      - name: Build & Install static FFmpeg
+        run: |
+          SRC_DIR="${{ github.workspace }}/target/ffmpeg-src"
+
+          git clone --depth 1 --branch n8.1.2 https://github.com/ffmpeg/ffmpeg $SRC_DIR
+          cd $SRC_DIR
+          ./configure --arch=arm64 --target-os=darwin --prefix="${{ env.FFMPEG_DIR }}" \
+            --pkg-config-flags="--static" \
+            --disable-runtime-cpudetect --disable-autodetect --disable-programs --disable-doc \
+            --disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-network \
+            --disable-encoders --disable-hwaccels --disable-muxers --disable-protocols --disable-devices --disable-filters \
+            --disable-asm --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 \
+            --disable-avx2 --disable-avx512 --disable-avx512icl --disable-aesni --disable-clmul \
+            --disable-shared --enable-static --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic \
+            --enable-muxer=matroska --enable-muxer=matroska_audio --enable-muxer=ass --enable-muxer=srt --enable-muxer=webvtt || {
+              echo "=== CONFIGURATION FAILED ==="
+              cat ffbuild/config.log
+              exit 1
+            }
+
+            make -j$(sysctl -n hw.ncpu)
+            make install
 
       - name: Build & Test Static Release
-        run: cargo test --release --features ffmpeg-build
+        run: cargo test --release --features ffmpeg-static
 
 
   linux-x64-static:
