Update workflows to generic cpu static builds

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,31 +15,95 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  linux-build:
-    runs-on: ubuntu-latest
+  cargo-publish-dry-run:
+    uses: ./.github/workflows/cargo-publish.yml
+    with:
+      additional_args: '--dry-run'
+
+
+  windows-builds:
+    runs-on: windows-latest
 
     env:
-      CFLAGS: "-march=x86-64 -mtune=generic"
-      CXXFLAGS: "-march=x86-64 -mtune=generic"
-      RUSTFLAGS: "-C target-cpu=x86-64"
+      FFMPEG_DIR: ${{ github.workspace }}/target/mux-media-ffmpeg
+
+    strategy:
+      matrix:
+        include:
+          - target: x86_64-pc-windows-msvc
+            msvc_arch: x64
+            mingw_msystem: MINGW64
+            ffmpeg_configure_flags: --arch=x86_64 --target-os=win64
+            release_suffix: Windows-x64
+
+          - target: i686-pc-windows-msvc
+            msvc_arch: x86
+            mingw_msystem: MINGW32
+            ffmpeg_configure_flags: --arch=x86 --target-os=win32
+            release_suffix: Windows-x32
+
+          - target: aarch64-pc-windows-msvc
+            msvc_arch: x64_arm64
+            mingw_msystem: MINGW64
+            ffmpeg_configure_flags: --arch=arm64 --target-os=win64 --enable-cross-compile --disable-asm
+            release_suffix: Windows-arm64
+
 
     steps:
       - uses: actions/checkout@v4
+      - uses: ilammy/msvc-dev-cmd@v1
+        with:
+          arch: ${{ matrix.msvc_arch }}
 
-      - name: Install dependencies
+      - name: Install Rust target
+        run: rustup target add ${{ matrix.target }}
+
+      - name: Install MSYS2 and Dependencies
+        uses: msys2/setup-msys2@v2
+        with:
+          msystem: ${{ matrix.mingw_msystem }}
+          update: true
+          path-type: inherit
+          install: >-
+            git
+            make
+            diffutils
+            yasm
+
+      - name: Build & Install static FFmpeg
+        shell: msys2 {0}
         run: |
-          sudo apt-get update
-          sudo apt-get install -y clang libavcodec-dev libavformat-dev libavutil-dev pkg-config nasm
+          SRC_DIR=$(cygpath -u "${{ github.workspace }}/target/ffmpeg-src")
+          PREFIX_DIR=$(cygpath -ua "${{ env.FFMPEG_DIR }}")
 
-      - name: Build Static
-        run: cargo build --release --features ffmpeg-build
+          git clone --depth 1 --branch n8.1.2 https://github.com/ffmpeg/ffmpeg $SRC_DIR
+          cd $SRC_DIR
+          ./configure --toolchain=msvc ${{ matrix.ffmpeg_configure_flags }} --prefix="$PREFIX_DIR" \
+            --pkg-config-flags="--static" --extra-cflags="-MD" \
+            --disable-runtime-cpudetect --disable-autodetect --disable-programs --disable-doc \
+            --disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-network \
+            --disable-encoders --disable-hwaccels --disable-muxers --disable-protocols --disable-devices --disable-filters \
+            --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 \
+            --disable-avx2 --disable-avx512 --disable-avx512icl --disable-aesni --disable-clmul \
+            --disable-shared --enable-static --enable-muxer=matroska --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic || {
+              echo "=== CONFIGURATION FAILED ==="
+              cat ffbuild/config.log
+              exit 1
+            }
+
+          make -j$(nproc)
+          make install
+
+      - name: Build
+        run: cargo build --release --features ffmpeg-static --target ${{ matrix.target }}
 
       - uses: actions/upload-artifact@v4
         with:
-          name: mux-media-Linux-x64
-          path: target/release/mux-media
+          name: mux-media-${{ matrix.release_suffix }}
+          path: target/${{ matrix.target }}/release/mux-media.exe
 
-  macos-build:
+
+  macos-arm64-build:
     runs-on: macos-latest
 
     steps:
@@ -48,7 +112,7 @@ jobs:
       - name: Install dependencies
         run: brew install pkg-config ffmpeg
 
-      - name: Build Static
+      - name: Build
         run: cargo build --release --features ffmpeg-build
 
       - uses: actions/upload-artifact@v4
@@ -56,39 +120,64 @@ jobs:
           name: mux-media-macOS-arm64
           path: target/release/mux-media
 
-  windows-build:
-    runs-on: windows-latest
+
+  linux-builds:
+    runs-on: ubuntu-latest
+
     env:
-      RUSTFLAGS: -l mfplat -l mf -l mfuuid -l strmiids -l ole32 -l uuid
+      FFMPEG_DIR: ${{ github.workspace }}/target/mux-media-ffmpeg
+
+      CFLAGS_x86_64_unknown_linux_musl: "-march=x86-64 -mtune=generic"
+      CXXFLAGS_x86_64_unknown_linux_musl: "-march=x86-64 -mtune=generic"
+      CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-cpu=generic"
+
+      CFLAGS_i686_unknown_linux_musl: "-march=pentium4 -mtune=generic -m32"
+      CXXFLAGS_i686_unknown_linux_musl: "-march=pentium4 -mtune=generic -m32"
+      CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_LINKER: "gcc"
+      CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-cpu=pentium4 -C link-args=-m32"
+
+    strategy:
+      matrix:
+        include:
+          - target: x86_64-unknown-linux-musl
+            dependencies: musl-tools
+            release_suffix: Linux-x64
+
+          - target: i686-unknown-linux-musl
+            dependencies: musl-tools gcc-multilib
+            release_suffix: Linux-x32
 
     steps:
       - uses: actions/checkout@v4
-      - uses: ilammy/msvc-dev-cmd@v1
-
-      - name: Set VCPKG_ROOT
-        shell: pwsh
-        run: |
-          $vcpkgPath = (where.exe vcpkg)[0]
-          $vcpkgRoot = Split-Path $vcpkgPath -Parent
-          echo "VCPKG_ROOT=$vcpkgRoot" >> $env:GITHUB_ENV
-          Write-Host "VCPKG_ROOT set to $vcpkgRoot"
 
       - name: Install dependencies
-        run: vcpkg install ffmpeg:x64-windows-static-md
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ${{ matrix.dependencies }}
 
-      - name: Build Static
-        run: cargo build --release --features ffmpeg-static
+      - name: Install Rust target
+        run: rustup target add ${{ matrix.target }}
+
+      - name: Build & Install static FFmpeg
+        run: |
+          mkdir -p ${{ env.FFMPEG_DIR }}
+          docker build -f Dockerfile.ffmpeg.${{ matrix.target }} -t ffmpeg-musl-builder .
+          docker create --name extractor ffmpeg-musl-builder
+          docker cp extractor:/ffmpeg_build/. ${{ env.FFMPEG_DIR }}
+          docker rm extractor
+
+      - name: Build
+        run: cargo build --release --features ffmpeg-static --target ${{ matrix.target }}
 
       - uses: actions/upload-artifact@v4
         with:
-          name: mux-media-Windows-x64
-          path: target/release/mux-media.exe
+          name: mux-media-${{ matrix.release_suffix }}
+          path: target/${{ matrix.target }}/release/mux-media
 
 
-  release:
-    name: Create GitHub Release
+  github-release:
     runs-on: ubuntu-latest
-    needs: [linux-build, macos-build, windows-build]
+    needs: [cargo-publish-dry-run, windows-builds, macos-arm64-build, linux-builds]
 
     steps:
       - uses: actions/download-artifact@v4
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -11,49 +11,98 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  run:
-    runs-on: ${{ matrix.os }}
-
-    strategy:
-      matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
-
+  windows-x64-static:
+    runs-on: windows-latest
     env:
-      WIN_FFMPEG_DOWNLOAD_URL: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
+      TARGET: x86_64-pc-windows-msvc
+      FFMPEG_DIR: ${{ github.workspace }}/target/x86_64-pc-windows-msvc/mux-media-ffmpeg
+      RUSTFLAGS: "-C target-cpu=generic"
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ilammy/msvc-dev-cmd@v1
+
+      - name: Install MSYS2 and Dependencies
+        uses: msys2/setup-msys2@v2
+        with:
+          msystem: MINGW64
+          update: true
+          path-type: inherit
+          install: >-
+            git
+            make
+            diffutils
+            yasm
+
+      - name: Build & Install static FFmpeg
+        shell: msys2 {0}
+        run: |
+          SRC_DIR=$(cygpath -u "${{ github.workspace }}/target/ffmpeg-src")
+          PREFIX_DIR=$(cygpath -ua "${{ env.FFMPEG_DIR }}")
+
+          git clone --depth 1 --branch n8.1.2 https://github.com/ffmpeg/ffmpeg $SRC_DIR
+          cd $SRC_DIR
+          ./configure --toolchain=msvc --arch=x86_64 --target-os=win64 --prefix="$PREFIX_DIR" \
+            --pkg-config-flags="--static" --extra-cflags="-MD" \
+            --disable-runtime-cpudetect --disable-autodetect --disable-programs --disable-doc \
+            --disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-network \
+            --disable-encoders --disable-hwaccels --disable-muxers --disable-protocols --disable-devices --disable-filters \
+            --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 \
+            --disable-avx2 --disable-avx512 --disable-avx512icl --disable-aesni --disable-clmul \
+            --disable-shared --enable-static --enable-muxer=matroska --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic || {
+              echo "=== CONFIGURATION FAILED ==="
+              cat ffbuild/config.log
+              exit 1
+            }
+
+          make -j$(nproc)
+          make install
+
+      - name: Build & Test Static Release
+        run: cargo test --release --features ffmpeg-static --target ${{ env.TARGET }}
+
+
+  macos-arm64-static:
+    runs-on: macos-latest
 
     steps:
       - uses: actions/checkout@v4
 
-      - name: Install dependencies (Linux)
-        if: matrix.os == 'ubuntu-latest'
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y clang libavcodec-dev libavformat-dev libavutil-dev pkg-config
-
-      - name: Install dependencies (Windows)
-        if: matrix.os == 'windows-latest'
-        run: |
-          $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
-          Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
-          Invoke-WebRequest "${env:WIN_FFMPEG_DOWNLOAD_URL}" -OutFile ffmpeg-release-full-shared.7z
-          7z x ffmpeg-release-full-shared.7z
-          mkdir ffmpeg
-          mv ffmpeg-*/* ffmpeg/
-          Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
-          Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"
-
-      - name: Install dependencies (macOS)
-        if: matrix.os == 'macos-latest'
+      - name: Install dependencies
         run: brew install pkg-config ffmpeg
 
-      - name: Build
-        run: cargo -vv build
+      - name: Build & Test Static Release
+        run: cargo test --release --features ffmpeg-build
 
-      - name: Test
-        run: cargo -vv test
 
-      - name: Build Release
-        run: cargo -vv build --release
+  linux-x64-static:
+    runs-on: ubuntu-latest
 
-      - name: Test Release
-        run: cargo -vv test --release
+    env:
+      TARGET: x86_64-unknown-linux-musl
+      FFMPEG_DIR: ${{ github.workspace }}/target/x86_64-unknown-linux-musl/mux-media-ffmpeg
+      CFLAGS: "-march=x86-64 -mtune=generic"
+      CXXFLAGS: "-march=x86-64 -mtune=generic"
+      RUSTFLAGS: "-C target-cpu=generic"
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install musl tools
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y musl-tools
+
+      - name: Install Rust target
+        run: rustup target add ${{ env.TARGET }}
+
+      - name: Build & Install static FFmpeg
+        run: |
+          mkdir -p ${{ env.FFMPEG_DIR }}
+          docker build -f Dockerfile.ffmpeg.${{ env.TARGET }} -t ffmpeg-musl-builder .
+          docker create --name extractor ffmpeg-musl-builder
+          docker cp extractor:/ffmpeg_build/. ${{ env.FFMPEG_DIR }}
+          docker rm extractor
+
+      - name: Build & Test Static Release
+        run: cargo test --release --features ffmpeg-static --target ${{ env.TARGET }}
